// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy603MXD9ukqFGt1Ik6tgzeP4_43qqdMY',
    appId: '1:1047144398112:web:a69e2afa71d232d3596b45',
    messagingSenderId: '1047144398112',
    projectId: 'cuenca-activa',
    authDomain: 'cuenca-activa.firebaseapp.com',
    storageBucket: 'cuenca-activa.firebasestorage.app',
    measurementId: 'G-07JQ69D0VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKbGhMpsDkZIzfviBZJtJo3P8iFD_GDEo',
    appId: '1:1047144398112:android:7078f5133ef309c2596b45',
    messagingSenderId: '1047144398112',
    projectId: 'cuenca-activa',
    storageBucket: 'cuenca-activa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkagxLQmh3wBEXIqL4BNEUpScwLV7tRos',
    appId: '1:1047144398112:ios:5ed8abf8264ca1ec596b45',
    messagingSenderId: '1047144398112',
    projectId: 'cuenca-activa',
    storageBucket: 'cuenca-activa.firebasestorage.app',
    iosBundleId: 'com.example.cuencaActivaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkagxLQmh3wBEXIqL4BNEUpScwLV7tRos',
    appId: '1:1047144398112:ios:5ed8abf8264ca1ec596b45',
    messagingSenderId: '1047144398112',
    projectId: 'cuenca-activa',
    storageBucket: 'cuenca-activa.firebasestorage.app',
    iosBundleId: 'com.example.cuencaActivaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy603MXD9ukqFGt1Ik6tgzeP4_43qqdMY',
    appId: '1:1047144398112:web:f78ff9ceb1fb1a58596b45',
    messagingSenderId: '1047144398112',
    projectId: 'cuenca-activa',
    authDomain: 'cuenca-activa.firebaseapp.com',
    storageBucket: 'cuenca-activa.firebasestorage.app',
    measurementId: 'G-5KX6GF84T2',
  );
}
